name: Deploy ON Push

on:
  push:
    branch: 
    - main

jobs:
  check:
    runs-on: ubuntu-latest
    step:
      name: Checkout-code
      uses: actions/checkout@v4
      name: HealthCheck
      run: echo "Health Check Passed"